port 1194
proto udp
dev tun

# Rutas de los certificados y claves
ca ca.crt
cert server.crt
key server.key
dh dh.pem

# Configuración de red
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt

# Mantener la conexión activa
keepalive 10 120
cipher AES-256-CBC
user nobody
group nogroup
persist-key
persist-tun

# Configuración de logs
status openvpn-status.log
log-append /var/log/openvpn.log
verb 3
