; GOLBERT V4.3 LTS - SIN CONFLICTO CON HAPROXY 443
pid = /var/run/stunnel4/stunnel.pid
cert = /etc/xray/certs/xray.pem
client = no
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1

[dropbear-444]
accept = 444
connect = 127.0.0.1:22

[openssh-445]
accept = 445
connect = 127.0.0.1:22

[openvpn-ssl]
accept = 442
connect = 127.0.0.1:1194
